# Bongosec App Copyright (C) 2017, Bongosec. (License GPLv2)
version: '3.7'

services:
  bongosec.master:
    image: bongosec/bongosec-manager:5.0.0
    hostname: bongosec.master
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://bongosec1.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=bongosec-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - master-bongosec-api-configuration:/var/ossec/api/configuration
      - master-bongosec-etc:/var/ossec/etc
      - master-bongosec-logs:/var/ossec/logs
      - master-bongosec-queue:/var/ossec/queue
      - master-bongosec-var-multigroups:/var/ossec/var/multigroups
      - master-bongosec-integrations:/var/ossec/integrations
      - master-bongosec-active-response:/var/ossec/active-response/bin
      - master-bongosec-agentless:/var/ossec/agentless
      - master-bongosec-wodles:/var/ossec/wodles
      - master-filebeat-etc:/etc/filebeat
      - master-filebeat-var:/var/lib/filebeat
      - ./config/bongosec_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec.master.pem:/etc/ssl/filebeat.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec.master-key.pem:/etc/ssl/filebeat.key
      - ./config/bongosec_cluster/bongosec_manager.conf:/bongosec-config-mount/etc/ossec.conf

  bongosec.worker:
    image: bongosec/bongosec-manager:5.0.0
    hostname: bongosec.worker
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    environment:
      - INDEXER_URL=https://bongosec1.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - worker-bongosec-api-configuration:/var/ossec/api/configuration
      - worker-bongosec-etc:/var/ossec/etc
      - worker-bongosec-logs:/var/ossec/logs
      - worker-bongosec-queue:/var/ossec/queue
      - worker-bongosec-var-multigroups:/var/ossec/var/multigroups
      - worker-bongosec-integrations:/var/ossec/integrations
      - worker-bongosec-active-response:/var/ossec/active-response/bin
      - worker-bongosec-agentless:/var/ossec/agentless
      - worker-bongosec-wodles:/var/ossec/wodles
      - worker-filebeat-etc:/etc/filebeat
      - worker-filebeat-var:/var/lib/filebeat
      - ./config/bongosec_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec.worker.pem:/etc/ssl/filebeat.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec.worker-key.pem:/etc/ssl/filebeat.key
      - ./config/bongosec_cluster/bongosec_worker.conf:/bongosec-config-mount/etc/ossec.conf

  bongosec1.indexer:
    image: bongosec/bongosec-indexer:5.0.0
    hostname: bongosec1.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - bongosec-indexer-data-1:/var/lib/bongosec-indexer
      - ./config/bongosec_indexer_ssl_certs/root-ca.pem:/usr/share/bongosec-indexer/certs/root-ca.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec1.indexer-key.pem:/usr/share/bongosec-indexer/certs/bongosec1.indexer.key
      - ./config/bongosec_indexer_ssl_certs/bongosec1.indexer.pem:/usr/share/bongosec-indexer/certs/bongosec1.indexer.pem
      - ./config/bongosec_indexer_ssl_certs/admin.pem:/usr/share/bongosec-indexer/certs/admin.pem
      - ./config/bongosec_indexer_ssl_certs/admin-key.pem:/usr/share/bongosec-indexer/certs/admin-key.pem
      - ./config/bongosec_indexer/bongosec1.indexer.yml:/usr/share/bongosec-indexer/opensearch.yml
      - ./config/bongosec_indexer/internal_users.yml:/usr/share/bongosec-indexer/opensearch-security/internal_users.yml

  bongosec2.indexer:
    image: bongosec/bongosec-indexer:5.0.0
    hostname: bongosec2.indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - bongosec-indexer-data-2:/var/lib/bongosec-indexer
      - ./config/bongosec_indexer_ssl_certs/root-ca.pem:/usr/share/bongosec-indexer/certs/root-ca.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec2.indexer-key.pem:/usr/share/bongosec-indexer/certs/bongosec2.indexer.key
      - ./config/bongosec_indexer_ssl_certs/bongosec2.indexer.pem:/usr/share/bongosec-indexer/certs/bongosec2.indexer.pem
      - ./config/bongosec_indexer/bongosec2.indexer.yml:/usr/share/bongosec-indexer/opensearch.yml
      - ./config/bongosec_indexer/internal_users.yml:/usr/share/bongosec-indexer/opensearch-security/internal_users.yml

  bongosec3.indexer:
    image: bongosec/bongosec-indexer:5.0.0
    hostname: bongosec3.indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - bongosec-indexer-data-3:/var/lib/bongosec-indexer
      - ./config/bongosec_indexer_ssl_certs/root-ca.pem:/usr/share/bongosec-indexer/certs/root-ca.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec3.indexer-key.pem:/usr/share/bongosec-indexer/certs/bongosec3.indexer.key
      - ./config/bongosec_indexer_ssl_certs/bongosec3.indexer.pem:/usr/share/bongosec-indexer/certs/bongosec3.indexer.pem
      - ./config/bongosec_indexer/bongosec3.indexer.yml:/usr/share/bongosec-indexer/opensearch.yml
      - ./config/bongosec_indexer/internal_users.yml:/usr/share/bongosec-indexer/opensearch-security/internal_users.yml

  bongosec.dashboard:
    image: bongosec/bongosec-dashboard:5.0.0
    hostname: bongosec.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - OPENSEARCH_HOSTS="https://bongosec1.indexer:9200"
      - BONGOSEC_API_URL="https://bongosec.master"
      - API_USERNAME=bongosec-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
    volumes:
      - ./config/bongosec_indexer_ssl_certs/bongosec.dashboard.pem:/usr/share/bongosec-dashboard/certs/bongosec-dashboard.pem
      - ./config/bongosec_indexer_ssl_certs/bongosec.dashboard-key.pem:/usr/share/bongosec-dashboard/certs/bongosec-dashboard-key.pem
      - ./config/bongosec_indexer_ssl_certs/root-ca.pem:/usr/share/bongosec-dashboard/certs/root-ca.pem
      - ./config/bongosec_dashboard/opensearch_dashboards.yml:/usr/share/bongosec-dashboard/config/opensearch_dashboards.yml
      - ./config/bongosec_dashboard/bongosec.yml:/usr/share/bongosec-dashboard/data/bongosec/config/bongosec.yml
      - bongosec-dashboard-config:/usr/share/bongosec-dashboard/data/bongosec/config
      - bongosec-dashboard-custom:/usr/share/bongosec-dashboard/plugins/bongosec/public/assets/custom
    depends_on:
      - bongosec1.indexer
    links:
      - bongosec1.indexer:bongosec1.indexer
      - bongosec.master:bongosec.master

  nginx:
    image: nginx:stable
    hostname: nginx
    restart: always
    ports:
      - "1514:1514"
    depends_on:
      - bongosec.master
      - bongosec.worker
      - bongosec.dashboard
    links:
      - bongosec.master:bongosec.master
      - bongosec.worker:bongosec.worker
      - bongosec.dashboard:bongosec.dashboard
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  master-bongosec-api-configuration:
  master-bongosec-etc:
  master-bongosec-logs:
  master-bongosec-queue:
  master-bongosec-var-multigroups:
  master-bongosec-integrations:
  master-bongosec-active-response:
  master-bongosec-agentless:
  master-bongosec-wodles:
  master-filebeat-etc:
  master-filebeat-var:
  worker-bongosec-api-configuration:
  worker-bongosec-etc:
  worker-bongosec-logs:
  worker-bongosec-queue:
  worker-bongosec-var-multigroups:
  worker-bongosec-integrations:
  worker-bongosec-active-response:
  worker-bongosec-agentless:
  worker-bongosec-wodles:
  worker-filebeat-etc:
  worker-filebeat-var:
  bongosec-indexer-data-1:
  bongosec-indexer-data-2:
  bongosec-indexer-data-3:
  bongosec-dashboard-config:
  bongosec-dashboard-custom:
