name: Integration tests for GitHub on Windows - Tier 0 and 1

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
  pull_request:
    paths:
        - ".github/workflows/4_testintegration_github-tier-0-1-win.yml"
        - "src/config/wmodules-github.c"
        - "src/bongosec_modules/wm_github.h"
        - "src/bongosec_modules/wm_github.c"
        - "src/win32/**"
        - "src/Makefile"
        - "tests/integration/conftest.py"
        - "tests/integration/test_github/**"

jobs:
  # Build the winagent on linux.
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Install wingw required to build the winagent.
      - name: Install dependencies
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
      - name: "Install a compatible CMake"
        uses: ./.github/actions/reinstall_cmake
      # Build winagent.
      - name: Build bongosec agent for windows
        run: |
          make deps -C src TARGET=winagent -j2
          make -C src TARGET=winagent -j2
      # Compress the files generated by the build.
      - name: Compress the winagent build
        run: cd .. && zip -r bongosec.zip bongosec
      # Make folder and save the compressed build as artifacts.
      - name: Save compressed build
        run: |
          mkdir -p src/winagent
          cp ../bongosec.zip src/winagent/bongosec.zip
      # Upload build artifacts.
      - name: Upload Artifact winagent
        uses: actions/upload-artifact@v4
        with:
          name: winagent
          path: src/winagent
  # Execute the tests on windows.
  run-test:
    needs: build
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: Add WiX toolkit to PATH
        shell: bash
        run: echo "${WIX}bin" >> $GITHUB_PATH
      # Download the compressed winagent build.
      - name: Download Artifact winagent
        uses: actions/download-artifact@v4
        with:
          name: winagent
          path: C:\winagent\
      # Decompress the winagent files.
      - name: Decompress bongosec
        run: |
          Expand-Archive -LiteralPath C:\winagent\bongosec.zip -DestinationPath C:\
      # Build the winagent installer.
      - name: Build bongosec installer
        run: |
          cd  C:\bongosec\src\win32
          .\bongosec-installer-build-msi.bat
      # Install the windows agent.
      - name: Install bongosec agent
        run: |
          cd  C:\bongosec\src\win32
          .\bongosec-agent--.msi /q BONGOSEC_MANAGER="127.0.0.1"
      # Download and install integration tests framework.
      - name: Download and install qa-integration
        run: |
          if (git ls-remote https://github.com/bongosec/qa-integration.git $env:BRANCH_NAME) {
              $QA_BRANCH = $env:BRANCH_NAME
          } elseif (git ls-remote https://github.com/bongosec/qa-integration.git $env:BRANCH_BASE) {
              $QA_BRANCH = $env:BRANCH_BASE
          } else {
              $QA_BRANCH = "main"
          }
          git clone -b $QA_BRANCH --single-branch https://github.com/bongosec/qa-integration.git
          pip install qa-integration/
          rm qa-integration/ -r -force
      # Run github integration tests.
      - name: Run github integration tests
        run: |
          cd C:\bongosec\tests\integration
          python -m pytest --tier 0 --tier 1 test_github\
